spring:
  config:
    activate:
      on-profile: local
  data:
    redis:
      host: localhost
      port: 6379

server:
  shutdown: graceful

---
spring:
  config:
    activate:
      on-profile: master
  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: slave
  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8081
